### ISSUE TITLE
Error adding allergy

### ISSUE THREAD

**Issue by s21290** [pjwstkIOprojekt/backendv2#109]
Paramedic can't add allergy.
![image](https://user-images.githubusercontent.com/80452231/212990023-77d69164-c496-4feb-a951-8ff8387a1323.png)

**Comment by s20462** [comment]
I can see in logs that: 
Cannot invoke "com.gary.backendv2.model.users.MedicalInfo.getAllergies()" because "userMedialInfo" is null

and that's expected, `Employee `accounts don't have `MedicalInfo `instance assigned to them. Fill add a filter that rejects this kind of requests

**Comment by s21290** [comment]
ok, my mistake
