### ISSUE TITLE
Password change/reset has no distinct error code when passed token/old password is incorrect

### ISSUE THREAD

**Issue by s20967** [pjwstkIOprojekt/backendv2#110]
Maybe change password/reset password endpoints could return other error code than 400 when old password/token is incorrect?
![image](https://user-images.githubusercontent.com/80460007/213008670-31246285-11ec-498d-80e8-8c1560006bbc.png)

**Comment by s20967** [comment]
Maybe we could return 401 code, just like incorrect login?
![image](https://user-images.githubusercontent.com/80460007/213009411-c2c9cfa0-52bc-4a01-853d-67041e7f7b1e.png)

**Comment by s20462** [comment]
will now return 403 in case of expired token

**Comment by s20967** [comment]
And what about changePassword endpoint? Will it also return 403 when old password is incorrect?

**Comment by s20462** [comment]
> And what about changePassword endpoint? Will it also return 403 when old password is incorrect?

Password reset throws only one exception, `400` when there is password mismatch
![image](https://user-images.githubusercontent.com/80460337/213502136-1bee3cf7-b6b7-4c11-adb9-256b4dba71b2.png)

**Comment by s20967** [comment]
OK
