### ISSUE TITLE
Ambulance path is still not split into parts

### ISSUE THREAD

**Issue by s20967** [pjwstkIOprojekt/backendv2#112]
We forgot to implement ambulance path partitioning.
![image](https://user-images.githubusercontent.com/80460007/213274242-d69b36f4-8a53-444e-be3a-fb25c751c2b6.png)

**Comment by s20967** [comment]
The ambulance paths should be individually assigned to handled incidents. (some example paths should also be seeded in)

**Comment by s20462** [comment]
logic implemented in #128 
and seeding will be done as a part of #123
