### ISSUE TITLE
Assigning medics to ambulances causes errors

### ISSUE THREAD

**Issue by s20967** [pjwstkIOprojekt/backendv2#114]
Trying to assign a medic to ambulance results in 500 error.

**Comment by s20967** [comment]
Trying to unassign a medic from an ambulance causes this issue as well.

**Comment by s20462** [comment]
![image](https://user-images.githubusercontent.com/80460337/213449779-c1f54142-5991-410d-bf49-d81ef3fa42f9.png)

And database
```
+------------+--------------+
|crew_crew_id|medics_user_id|
+------------+--------------+
|1           |5             |
+------------+--------------+
```

```
+------------+---------------+--------------+-------------+------------------+-----------------+-----+----------+------------+------------+
|ambulance_id|ambulance_class|ambulance_type|license_plate|latitude          |longitude        |seats|history_id|crew_crew_id|inventory_id|
+------------+---------------+--------------+-------------+------------------+-----------------+-----+----------+------------+------------+
|1           |BASIC          |A             |LBI 55362    |20.977728377285462|52.21934563858324|9    |1         |1           |1           |
+------------+---------------+--------------+-------------+------------------+-----------------+-----+----------+------------+------------+

```

**Comment by s20462** [comment]
Unassignment looks good as well
![image](https://user-images.githubusercontent.com/80460337/213450661-6318cbbc-991d-466f-81e5-e6abcbed621f.png)

![image](https://user-images.githubusercontent.com/80460337/213450721-d4aa1844-89ca-4bac-a9be-cc916fcba105.png)

**Comment by s20967** [comment]
It doesn't work onmy side
![image](https://user-images.githubusercontent.com/80460007/213451375-07588ced-cd98-4b05-88cb-584d21e9e375.png)
![image](https://user-images.githubusercontent.com/80460007/213451213-f381ca03-3087-4a71-8684-5664281d3c8d.png)

**Comment by s20462** [comment]
show full request you're sending
