### ISSUE TITLE
GetAllSchedules endpoint returns lacking info

### ISSUE THREAD

**Issue by s20967** [pjwstkIOprojekt/backendv2#117]
GetAllSchedules endpoint returns only the schedule info itself but no info about users the schedules belong to.

**Comment by s20462** [comment]
There was a field `id` that related to user id of the user some schedule was assigned to
changed to `userId` for more readability

![image](https://user-images.githubusercontent.com/80460337/213468905-a6275100-ca0e-4c96-8895-17da3cc9213a.png)

**Comment by s20462** [comment]
reverted back to id to prevent application breaking from changed response field name
