### ISSUE TITLE
Data seeding with objects connections

### ISSUE THREAD

**Issue by s20967** [pjwstkIOprojekt/backendv2#123]
Implement data seeding with objects connections (the best way to do this would be to seed data with code).

**Comment by s20967** [comment]
The seeding should also generate actual values instead of nulls. Those null values cause errors on frontend.
![image](https://user-images.githubusercontent.com/80460007/213539859-d4d0841b-c349-4b83-a7df-9bf97f15bb89.png)
![image](https://user-images.githubusercontent.com/80460007/213540157-65e3d734-9c67-45e6-9016-dc020e51bdb1.png)

**Comment by s20462** [comment]
> Those null values cause errors on frontend.
nullable fields are option IIRC

**Comment by s20967** [comment]
I understand, but some of those values aren't nullable.
![image](https://user-images.githubusercontent.com/80460007/214111245-963fee46-c80c-47d3-9c1e-a926644b4fba.png)
