### ISSUE TITLE
Shift start sometimes doesn't work

### ISSUE THREAD

**Issue by s20967** [pjwstkIOprojekt/backendv2#124]
Sometimes shift start doesn't work. I don't know why.
![image](https://user-images.githubusercontent.com/80460007/213544052-d2cea924-e158-4a67-bda2-d17a41b35d7a.png)

**Comment by s20967** [comment]
It seems that shift/end endpoint doesn't actually end the shift.

This call was made after multiple calls of shift/end endpoint.
![image](https://user-images.githubusercontent.com/80460007/213728631-1ac64f4b-6a0d-40e8-8280-d92e0d9043d9.png)

**Comment by s20462** [comment]
It was assumed that you can only start and end shift once per day
![image](https://user-images.githubusercontent.com/80460337/213887743-c0fd407f-1148-4dd9-96ac-0aefc7a97eea.png)

can delete it, doesn't break any logic further

**Comment by s20967** [comment]
I can implement a confirmation popup to prevent miss-clicks
