### ISSUE TITLE
Feature request: Endpoint for adding victim information by a medic

### ISSUE THREAD

**Issue by s20610** [pjwstkIOprojekt/backendv2#126]

**Comment by s20967** [comment]
You should be a bit more specific about what you expect. Are we talking about adding victim information manually, scanning their band code to retrieve their data or both?

**Comment by s20610** [comment]
Manually adding victim info based on what medic puts in fields from mobile app view. Ideally a POST call with medic token and JSON body

**Comment by s20462** [comment]
I don't think I get it

Medic puts some basic info about casualties to the Incident it was assigned to?
Then we can query by Incident and get all information about people who suffered from this Incident?

POST /incident/{id}/casualities
some basic info in the body
and Medic info is inferred from the token

and then
GET /incident/{id}/casualties
which should return list of people 

right?

**Comment by s20610** [comment]
Right now the view in app looks like that
![Screenshot 2023-01-22 125255](https://user-images.githubusercontent.com/56875192/213914367-047262f0-bc7e-4091-85f9-af9624acf7a4.png)

But I think option to add simple information about casualties is better so let's go with @s20462 idea

**Comment by s20462** [comment]
implemented in #131
