### ISSUE TITLE
Tutorial average rating doesn't update

### ISSUE THREAD

**Issue by s20967** [pjwstkIOprojekt/backendv2#98]
Tutorial average rating is not updated when a review is added/changed.

**Comment by s20462** [comment]
Looks good on server side

Debug logs:
![image](https://user-images.githubusercontent.com/80460337/212785270-81f86538-7467-4c03-bb51-1e81ad5f6b40.png)
and response
![image](https://user-images.githubusercontent.com/80460337/212785305-a5183762-9e58-4275-b9c6-0c21f07ccc45.png)

**Comment by s20967** [comment]
The issue is resolved.
